### ISSUE TITLE
.done() crashes node

### ISSUE THREAD

**Issue by thomasmeadows** [bvalosek/infusionsoft-api#12]
The bug is with .done() on line 290 in lib/Queryable.js.  If XML-RPC fails to parse and throws an error, when it falls into this done() it will create a uncatchable segment fault in the app and shut it down.   

This is a flaw in the way .done works with promises.  Unfortunately since infusionsoft often throws non xml rpc responses it can cause node crashes extremely often.

In order to resolve the issue it needs to be replaced with a .then and .catch as apposed to .done.

**Comment by bvalosek** [comment]
I believe this is solved by https://github.com/bvalosek/infusionsoft-api/pull/14 ?

**Comment by thomasmeadows** [comment]
@bvalosek yes resolved now
